name: CI

on:
  push:
  pull_request:

jobs:
  test-fee-math:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trident-app/services/fee_math
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pytest -q
