name: validate-fogbreaker-pulse

on:
  pull_request:
    branches: ["reset/scaffold"]
    paths:
      - "fogbreaker-app/pulse/**"
      - ".github/workflows/validate-fogbreaker-pulse.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Micro-Grant — FOGBREAKER Pulse v0.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1) Path confinement: only pulse/** (and this file)
      - name: Path confinement (only fogbreaker-app/pulse/**)
        run: |
          set -euo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          git fetch --no-tags --prune origin
          CHANGED="$(git diff --name-only "$BASE_SHA"...HEAD || true)"
          echo "Changed files:"; echo "${CHANGED:-<none>}"
          ALLOWED='^(fogbreaker-app/pulse/|\.github/workflows/validate-fogbreaker-pulse\.yml$)'
          BAD=0
          for f in ${CHANGED}; do
            if ! echo "$f" | grep -Eq "$ALLOWED"; then
              echo "❌ Forbidden change: $f"; BAD=1
            fi
          done
          [ $BAD -eq 0 ] || { echo "Only fogbreaker-app/pulse/** allowed."; exit 1; }
          echo "✅ Allowed paths only."

      # 2) Detect if pulse/** changed (so maintenance PRs can pass)
      - name: Detect if pulse files changed
        id: pulse_changed
        run: |
          set -euo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          git fetch --no-tags --prune origin
          CHANGED="$(git diff --name-only "$BASE
